# utils/reports.py

from datetime import datetime


def generate_usage_report(inventory_manager, period="monthly"):
    """
    Generate a usage cost report for all items in the inventory manager for a given period.

    :param inventory_manager: An instance of TugboatInventory.
    :param period: One of 'monthly', 'quarterly', or 'yearly'.
    :return: A dictionary mapping tugboat names to total usage cost.
    """
    report = {}
    for tugboat, items in inventory_manager.inventory.items():
        total_cost = 0.0
        for item in items.values():
            total_cost += item.get_usage_cost(period)
        report[tugboat] = total_cost
    return report


def generate_inventory_report(inventory_manager):
    """
    Generate a comprehensive inventory report with details for each item.

    :param inventory_manager: An instance of TugboatInventory.
    :return: A dictionary mapping tugboat names to lists of item data.
    """
    report = {}
    for tugboat, items in inventory_manager.inventory.items():
        tugboat_data = []
        for item in items.values():
            item_data = {
                'item_number': item.item_number,
                'name': item.name,
                'category': item.category,
                'location': item.location,
                'quantity': item.quantity,
                'cost_per_unit': item.cost,
                'total_value': item.quantity * item.cost,
                'min_stock': item.min_stock,
                'safety_stock': item.safety_stock,
                'reorder_needed': item.check_reorder(),
                'expiry_date': item.expiry_date.strftime("%Y-%m-%d") if item.expiry_date else None
            }
            tugboat_data.append(item_data)
        report[tugboat] = tugboat_data
    return report


def print_usage_report(report, period):
    """
    Print the usage report in a human-readable format.

    :param report: The report dictionary generated by generate_usage_report.
    :param period: The reporting period (for header).
    """
    print(f"Usage Report ({period.capitalize()}):")
    for tugboat, cost in report.items():
        print(f"  {tugboat}: ${cost:.2f}")


def print_inventory_report(report):
    """
    Print the inventory report in a human-readable format.

    :param report: The report dictionary generated by generate_inventory_report.
    """
    print("Inventory Report:")
    for tugboat, items in report.items():
        print(f"\nTugboat: {tugboat}")
        for item in items:
            print(f"  Item {item['item_number']} - {item['name']} | Category: {item['category']} | "
                  f"Location: {item['location']} | Quantity: {item['quantity']} | "
                  f"Total Value: ${item['total_value']:.2f} | Reorder Needed: {item['reorder_needed']}")
